apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  namespace: {{ default .Release.Namespace .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
    version: {{ .Values.image.tag }}
    env: {{ .Values.global.env }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: mongo
      protocol: TCP
      name: default
  selector:
    app: {{ .Values.appName }}
    env: {{ .Values.global.env }}
