replicaCount: 1
appName: frontend
env: development

image:
  name: khaosdoctor/event-sourcing-frontend
  tag: latest

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
  hosts:
    - host: chart-example.local
      paths: []

environment:
  NODE_ENV: development