global:
  replicaCount: 1
  env: development
  imageTag: latest

frontend:
  appName: frontend

  image:
    name: khaosdoctor/event-sourcing-frontend

  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: addon-http-application-routing
    hostname: demo-app.f8b8184f326740f9b169.eastus.aksapp.io

  environment:
    NODE_ENV: development

backend:
  appName: backend

  image:
    name: khaosdoctor/event-sourcing-backend

  service:
    type: ClusterIP
    port: 80

  environment:
    NODE_ENV: development

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: addon-http-application-routing
    hostname: api-demo-app.f8b8184f326740f9b169.eastus.aksapp.io