version: "3.7"

services:
  backend:
    build: ./backend
    environment:
      DATABASE_MONGODB_URI: mongodb://database:27017
      DATABASE_MONGODB_DBNAME: ship_manager
      NODE_ENV: ${NODE_ENV:-development}
    ports:
      - "3000:3000"
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
      args:
        VUE_APP_BACKEND_BASE_URL: http://localhost:3000
        VUE_APP_PROJECT_TITLE: "Ship Manager 2.0"
    ports:
      - "80:80"
    depends_on:
      - backend

  database:
    image: mvertes/alpine-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db

volumes:
  mongodb:
