apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: {{ default .Release.Namespace .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
    env: {{ .Values.global.env }}
    version: {{ .Values.global.imageTag }}
spec:
  replicas: {{ .Values.global.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
      env: {{ .Values.global.env }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
        env: {{ .Values.global.env }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.name }}:{{ .Values.global.imageTag }}"
          imagePullPolicy: IfNotPresent
          env:
            - name: DATABASE_MONGODB_URI
              value: {{ (default (tpl "mongodb://mongodb.{{.Release.Namespace}}.svc.cluster.local" .) .Values.environment.DATABASE_MONGODB_URI) | quote}}
            - name: DATABASE_MONGODB_DBNAME
              value: {{ (default (tpl "ship-manager-{{.Release.Namespace}}" .) .Values.environment.DATABASE_MONGODB_DBNAME) | quote }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http