apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.appName }}
  namespace: {{ default .Release.Namespace .Values.frontend.namespace }}
  labels:
    app: {{ .Values.frontend.appName }}
    env: {{ .Values.global.env }}
    version: {{ .Values.global.imageTag }}
spec:
  replicas: {{ .Values.global.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.frontend.appName }}
      env: {{ .Values.global.env }}
  template:
    metadata:
      labels:
        app: {{ .Values.frontend.appName }}
        env: {{ .Values.global.env }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.frontend.image.name }}:{{ .Values.global.imageTag }}"
          imagePullPolicy: IfNotPresent
          env:
            - name: NODE_ENV
              value: {{ .Values.frontend.environment.NODE_ENV }}
            - name: VUE_APP_BACKEND_BASE_URL
              value: {{ (default (tpl "http://backend.{{.Release.Namespace}}.svc.cluster.local" .) .Values.frontend.environment.VUE_APP_BACKEND_BASE_URL) | quote}}
            - name: VUE_APP_PROJECT_TITLE
              value: {{ (default (tpl "Ship Manager ({{.Values.frontend.image.tag}})" .) .Values.frontend.environment.VUE_APP_PROJECT_TITLE) | quote }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http