apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.frontend.appName }}
  namespace: {{ default .Release.Namespace .Values.frontend.namespace }}
  labels:
    app: {{ .Values.frontend.appName }}
    env: {{ .Values.global.env }}
    version: {{ .Values.global.imageTag}}
  {{- with .Values.frontend.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - host: {{ .Values.frontend.ingress.hostname }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ .Values.frontend.appName }}
              servicePort: http